name: Crawler Agenda Automatizado
on:
  schedule:
    - cron: '0 */2 * * *' # Se ejecuta en el minuto 0 de cada 2 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Actualizado a una versión más reciente

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Crawler
        env:
          # --- SECRETOS ---
          # Aquí GitHub inyectará la URL de Render que configuraremos en la pestaña Settings
          API_URL_AGENDA: ${{ secrets.API_URL_AGENDA }}
          
          # --- VARIABLES PÚBLICAS ---
          # Si algún día cambian de dominio, solo lo modificas aquí
          TVLIBRE_DOMAIN: "https://tvlibre-online.com"
          DL_DOMAIN: "https://deporte-libre.online"
        run: |
          # Navegamos a la carpeta scripts para evitar problemas de importación con los otros módulos
          cd scripts
          python crawler_agenda.py
